# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VTB_HACKATHON_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CameraManager', '~> 5.1'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  # Pods for VTB_HACKATHON_iOS

end
